name: "Build & Release"

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
          architecture: x64

      - name: Install Android SDK
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0"

      - run: flutter clean
      - run: flutter pub get
      - run: chmod +x android/gradlew

      - run: flutter build apk --release --no-daemon --verbose

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
